### ISSUE TITLE
fuelup crashes when trying to install components

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuelup#444]
### Problem

I noticed that my fuelup has been failing to install any toolchains/components and crashes when it tries to do so:

```
RUST_BACKTRACE=full fuelup toolchain install latest

thread 'main' panicked at 'no entry found for key', src/download.rs:78:27
stack backtrace:
   0:        0x1029596c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3c406a4521928e59
   1:        0x102975b98 - core::fmt::write::hc60df9bae744c40c
   2:        0x102953ba4 - <std::io::Guard as core::ops::drop::Drop>::drop::hd1119ab4bcc45dfd
   3:        0x1029594d4 - <std::time::SystemTimeError as core::fmt::Display>::fmt::ha72e7e57e8c06abb
   4:        0x10295ab30 - std::panicking::default_hook::hd2988fbcc86fdc46
   5:        0x10295a888 - std::panicking::default_hook::hd2988fbcc86fdc46
   6:        0x10295b154 - std::panicking::rust_panic_with_hook::h01730ad11d62092c
   7:        0x10295af74 - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h978adec8182eb460
   8:        0x102959b28 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3c406a4521928e59
   9:        0x10295acd0 - _rust_begin_unwind
  10:        0x10298c50c - core::panicking::panic_fmt::hf1070b3fc33229fa
  11:        0x1029741c0 - <core::panic::panic_info::PanicInfo as core::fmt::Display>::fmt::h005fb4b8c1173c7d
  12:        0x102974184 - <core::panic::panic_info::PanicInfo as core::fmt::Display>::fmt::h005fb4b8c1173c7d
  13:        0x10298c4d8 - core::option::expect_failed::h044ad95fca40270b
  14:        0x102792a58 - fuelup::download::DownloadCfg::from_package::ha75a7414b2a275b7
  15:        0x1027bac74 - <fuelup::commands::default::DefaultCommand as clap::derive::Args>::augment_args::hf5a2eaf61cd11678
  16:        0x10278dd5c - <fuelup::settings::_::<impl serde::de::Deserialize for fuelup::settings::Settings>::deserialize::__Visitor as serde::de::Visitor>::expecting::h34a2959aacf82938
  17:        0x1027caf74 - fuelup::ops::fuelup_toolchain::install::install::h0b2036a80a5dee5e
  18:        0x1027b15f0 - fuelup::fuelup_cli::fuelup_cli::hc4222d28798f9920
  19:        0x102761988 - __mh_execute_header
  20:        0x102766904 - _main
  21:        0x102762974 - _main
  22:        0x10294dcf8 - std::rt::lang_start_internal::h24d09c16ec322e75
  23:        0x102761d2c - _main
```

This also happens when fuelup tries to install the default toolchain at the end of the installation script for fuelup itself.

### Steps

Try to install `fuelup` via the installation script in the readme
or 
Run `fuelup toolchain install latest`

### Fuelup version

```console
0.19.1
```

### Installed components

```console
fuelup - Up to date : 0.19.1
```
```

**Comment by ra0x3** [comment]
Issue also happened to me. Here's my results:

Showing that no `fuelup` is on my machine:
```
ls -la ~/.fuelup
ls: /Users/rashad/.fuelup: No such file or directory
```

Trying to download fuelup
```
> curl --proto '=https' --tlsv1.2 -sSf https://install.fuel.network/fuelup-init.sh | sh

fuelup uses "/Users/rashad/.fuelup" as its home directory to manage the Fuel toolchain, and will install binaries there.

To use the toolchain, you will have to configure your PATH, which tells your machine where to locate fuelup and the Fuel toolchain.

If permitted, fuelup-init will configure your PATH for you by running the following:

    echo "export PATH="$HOME/.fuelup/bin:$PATH"" >> /Users/rashad/.zshrc

Would you like fuelup-init to modify your PATH variable for you? (N/y)
y

fuelup will modify your PATH variable for you.

info: downloading fuelup 0.19.1

thread 'main' panicked at 'no entry found for key', src/download.rs:78:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

fuelup 0.19.1 has been installed in /Users/rashad/.fuelup/bin. To fetch the latest toolchain containing the forc and fuel-core binaries, run 'fuelup toolchain install latest'. To generate completions for your shell, run 'fuelup completions --shell=SHELL'.

/Users/rashad/.fuelup/bin already exists in your PATH.
```

System is:
```
Darwin Rashads-MacBook-Air.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 arm64
```
