### ISSUE TITLE
bug: `fuelup check latest` test failing

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/fuelup#465]
running `cargo test --locked --workspace` on master:

```sh
running 1 test
test fuelup_check ... FAILED

failures:

---- fuelup_check stdout ----
thread 'fuelup_check' panicked at 'assertion failed: output.stdout.contains(&latest)', tests/check.rs:26:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by eureka-cpu** [comment]
Ran it again, getting a different failure:
```sh
running 5 tests
test fuelup_show_override ... FAILED
test fuelup_show_custom ... ok
test fuelup_show_latest ... ok
test fuelup_show_latest_then_override ... ok
test fuelup_show_and_switch ... ok

failures:

---- fuelup_show_override stdout ----
thread 'fuelup_show_override' panicked at 'assertion failed: stdout.contains(expected_stdout)', tests/show.rs:211:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    fuelup_show_override

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.94s
```
